### ISSUE TITLE
Why does a proposal.owner can vote on behalf of someone else?

### ISSUE THREAD

**Issue by assafmo** [daostack/daostack#66] opened 2017-08-10 21:59 UTC
https://github.com/daostack/daostack/blob/6a2a928cc130e78638d4f440112e11c147f4b0b3/contracts/VotingMachines/SimpleVote.sol#L106-L108

What is preventing a malicious `proposal.owner` rapidly voting for its proposal "on behalf" of other voters (just call `vote` with other voters' addresses) and triggering a successful `executeProposal(_proposalId)` in https://github.com/daostack/daostack/blob/6a2a928cc130e78638d4f440112e11c147f4b0b3/contracts/VotingMachines/SimpleVote.sol#L133 after enough votes?

I think that `_voter` should always be `msg.sender`. 

Am I missing someting? When and why would a voter **need to** vote on behalf of someone else?

**Comment by leviadam** [comment] 2017-08-11 03:54
The SimpleVote contract is Voting as a service.
There is no problem of the owner voting for someone because the owner in the usual case is just a scheme.
The idea is to allow the scheme to vote in the name of the agent that proposed the vote.

**Comment by jellegerbrandy** [comment] 2017-08-11 08:52
I'm just adding these observations:

  * Even if it is intended behavior and so not a  bug, having an all-power proposal owner _is_  a  complication. It means that the  voting procedure is about as secure as the voting contract itself _together with the owner_, which could in theory be any contract (or user). This is not very good practice: we'd like to have a clear division of responsibility to keep our thinking about security sane. 
 * I looked in the code, and the _only_ use I can see for the `owner` argument is to vote automatically for a  proposal that is submitted. This is basically a UX feature and so has no real place on the solidity level, and it could  just as well be a separate transaction.
  * "triggering a successful executeProposal(_proposalId)" -> Again, this could be _any_ executable, so it is hard to say things in general, but the answer here is that the controller will be in charge of security here (de facto saying "I only do stuff that is aksed for by my schemes, and my schemes are responsible for the proposal security")

I'd be leaning towards simplification: taking the owner out, (and thus not having an automatic "yes" vote on proposing).

**Comment by leviadam** [comment] 2017-08-11 09:20
It is indeed not good to solve UI problems on the blockchain.
Here it is a very annoying UI issue.
I tend to agree we should change it. But the UI cost is quite significant.

**Comment by assafmo** [comment] 2017-08-11 09:57
Thank you for the quick responses!

I believe that [simplicity follows complexity](http://mitadmissions.org/blogs/entry/the-complexity-of-simpliciyy). The simpler the contract will be, it will have less bugs.

**Comment by leviadam** [comment] 2017-08-11 10:08
I totally agree. 
But in such a big system there are sometimes annoying constraints. 

Anyway,
Thank you for your questions and comments.

**Comment by assafmo** [comment] 2017-08-13 17:56
@leviadam - Regarding the UI comment.
I think that only `constant` functions should return values, and for every state change an appropriate event should be logged.

That way each UI component will listen to the logs of its choosing and update as new events arrive.
For exmaple, a UI component that shows current proposal state:
- (a) The component can aggregate logs, e.g. count `VoteProposal` events as they come and show the current state or
- (b) A new event will be created `event ProposalState(bytes32 indexed _proposalId, uint _yes, uint _no)` and it will be logged every time a change is made to `proposal.voted`

This is only my opinion and I might as well be wrong, but by creating appropriate events and making UI components rely only on listening to events, contracts can be simplified and it will be harder to create bugs.

**Closed** 2017-08-20 21:24 UTC
